Repository angel-bridge/Back-end, pull requests merged in 2024-12, with the labels that each got.

#13 feat: 어드민 페이지 전체 API 구현
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/controller/AdminBannerController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/dto/request/AdminBannerRequestDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/dto/response/AdminBannerResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/entity/Banner.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/service/BannerService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/blog/controller/AdminBlogController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/blog/dto/request/AdminBlogRequestDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/blog/dto/response/AdminBlogResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/blog/entity/Blog.java
  src/main/java/angel_bridge/angel_bridge_server/domain/blog/service/BlogService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/controller/AdminEducationController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/dto/request/AdminEducationRequestDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/dto/response/AdminEducationResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/entity/Education.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/entity/RecruitmentStatus.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/service/EducationService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/entity/Member.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/service/AuthService.java
  src/main/java/angel_bridge/angel_bridge_server/global/common/response/CommonResponse.java
  src/main/java/angel_bridge/angel_bridge_server/global/config/S3Config.java
  src/main/java/angel_bridge/angel_bridge_server/global/config/SecurityConfig.java
  src/main/java/angel_bridge/angel_bridge_server/global/config/SwaggerConfig.java
  src/main/java/angel_bridge/angel_bridge_server/global/exception/ExceptionCode.java
  src/main/java/angel_bridge/angel_bridge_server/global/exception/ExceptionResponse.java
  src/main/java/angel_bridge/angel_bridge_server/global/oauth2/CustomSuccessHandler.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/BannerRepository.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/BlogRepository.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EducationRepository.java
Labels: ✨feat

#16 feat: 메인 페이지 api 작업
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/controller/BannerController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/dto/response/BannerResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/service/BannerService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/blog/controller/BlogController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/blog/dto/response/BlogResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/blog/service/BlogService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/controller/EducationController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/dto/RecommendationProgramResponse.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/entity/Education.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/service/EducationService.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/BannerRepository.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/BlogRepository.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EducationRepository.java
Labels: ✨feat

#21 feat: 카카오 프로필 이미지 받아오는 로직 추가
  src/main/java/angel_bridge/angel_bridge_server/domain/member/entity/Member.java
  src/main/java/angel_bridge/angel_bridge_server/global/oauth2/dto/KakaoResponse.java
  src/main/java/angel_bridge/angel_bridge_server/global/oauth2/dto/OAuth2Response.java
  src/main/java/angel_bridge/angel_bridge_server/global/oauth2/dto/OAuthUserDTO.java
  src/main/java/angel_bridge/angel_bridge_server/global/oauth2/service/CustomOAuth2UserService.java
Labels: ✨feat

#23 feat: 회원 정보 API 구현
  src/main/java/angel_bridge/angel_bridge_server/domain/education/controller/EducationController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/dto/response/RecommendationProgramResponse.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/service/EducationService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/controller/AuthController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/controller/MemberController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/dto/request/AuthRequestDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/dto/request/MemberRequestDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/dto/response/MemberResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/entity/Member.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/entity/ProfileImageType.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/service/AuthService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/service/MemberService.java
  src/main/java/angel_bridge/angel_bridge_server/global/exception/ExceptionCode.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/MemberRepository.java
Labels: ✨feat

#25 fix : 이미지 링크를 getImageUrl 로 응답 반환
  src/main/java/angel_bridge/angel_bridge_server/domain/member/dto/response/MemberResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/service/MemberService.java
Labels: 🛠️fix

#26 feat: 프로그램 조회 api
  src/main/java/angel_bridge/angel_bridge_server/domain/education/controller/EducationController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/dto/response/EducationDetailResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/dto/response/EducationResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/dto/response/RecommendationProgramResponse.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/service/EducationService.java
  src/main/java/angel_bridge/angel_bridge_server/global/config/SecurityConfig.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EducationRepository.java
Labels: ✨feat

#28 feat: 교육 프로그램 검색바 API
  src/main/java/angel_bridge/angel_bridge_server/domain/education/controller/EducationController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/service/EducationService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/dto/response/MemberResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/global/config/SecurityConfig.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EducationRepository.java
Labels: ✨feat, 🌿refactor
