Repository angel-bridge/Back-end, pull requests merged in 2025-01, with the labels that each got.

#31 feat : 수강 내역 조회 API 구현
  build.gradle
  src/main/java/angel_bridge/angel_bridge_server/AngelBridgeServerApplication.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/controller/EnrollmentController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/dto/response/EnrollmentResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/entity/Enrollment.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/entity/EnrollmentStatus.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/service/EnrollmentService.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EnrollmentRepository.java
Labels: ✨feat

#34 fix: enrollment, education 작업 마무리
  src/main/java/angel_bridge/angel_bridge_server/domain/education/service/EducationService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/controller/EnrollmentController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/service/EnrollmentService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/member/controller/MemberController.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EducationRepository.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EnrollmentRepository.java
Labels: ✨feat, 🛠️fix

#37 feat: 결제 관련 api 구현
  build.gradle
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/entity/Enrollment.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/entity/EnrollmentStatus.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/controller/PaymentController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/request/ConfirmPaymentRequestDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/response/CancelPaymentRequestDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/response/CanceledPaymentResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/response/CompletePaymentResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/response/ConfirmPaymentResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/response/PaymentResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/entity/PaymentMethod.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/entity/PaymentStatus.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/entity/TossPayment.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/service/PaymentService.java
  src/main/java/angel_bridge/angel_bridge_server/global/config/WebClientConfig.java
  src/main/java/angel_bridge/angel_bridge_server/global/exception/ExceptionCode.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EnrollmentRepository.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/TossPaymentRepository.java
Labels: ✨feat

#39 feat: 결제 내역 마무리
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/controller/PaymentController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/service/PaymentService.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EnrollmentRepository.java
Labels: ✨feat

#43 feat: 교육 페이지 배너 이미지 조회 API
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/controller/BannerController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/service/BannerService.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/BannerRepository.java
Labels: ✨feat

#44 Fix : 전체 페이지네이션 수정
  src/main/java/angel_bridge/angel_bridge_server/domain/assignment/service/AssignmentService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/controller/EducationController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/service/EducationService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/controller/EnrollmentController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/enrollment/service/EnrollmentService.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/controller/PaymentController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/response/CanceledPaymentResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/response/CompletePaymentResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/response/PaymentResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/service/PaymentService.java
  src/main/java/angel_bridge/angel_bridge_server/global/common/response/PagedResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EnrollmentRepository.java
Labels: 🛠️fix, 🌿refactor

#50 Refactor: 배너 리팩토링 및 카카오 redirect-uri 수정
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/controller/AdminBannerController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/dto/request/AdminBannerRequestDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/dto/response/AdminBannerResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/entity/Banner.java
  src/main/java/angel_bridge/angel_bridge_server/domain/banner/service/BannerService.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/BannerRepository.java
  src/main/resources/application.yml
Labels: 🛠️fix, 🌿refactor

#51 chore: cookie https 허용
  src/main/java/angel_bridge/angel_bridge_server/domain/member/service/AuthService.java
  src/main/java/angel_bridge/angel_bridge_server/global/oauth2/CustomSuccessHandler.java
Labels: 📃chore

#54 feat: 결제 api 마무리
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/controller/PaymentController.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/dto/request/SaveAmountRequestDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/payment/service/PaymentService.java
  src/main/java/angel_bridge/angel_bridge_server/global/exception/ExceptionCode.java
  src/main/java/angel_bridge/angel_bridge_server/global/oauth2/CustomSuccessHandler.java
Labels: ✨feat

#57 Fix: 교육 프로그램 상태 스케줄링
  src/main/java/angel_bridge/angel_bridge_server/domain/education/entity/Education.java
  src/main/java/angel_bridge/angel_bridge_server/domain/education/service/EducationService.java
  src/main/java/angel_bridge/angel_bridge_server/global/repository/EducationRepository.java
Labels: ✨feat

#60 fix: 수강완료 미션수행률 추가
  src/main/java/angel_bridge/angel_bridge_server/domain/assignment/dto/response/AssignmentResponseDto.java
  src/main/java/angel_bridge/angel_bridge_server/domain/assignment/service/AssignmentService.java
Labels: 🛠️fix
